version: "3.9"

services:
  jenkins:
    container_name: jenkins
    restart: unless-stopped
    image: jenkins/jenkins:latest
    user: root
    ports:
      - 8080
      - 5000
    volumes:
      - /var/lib/jenkins:/var/lib/jenkins
      - /home/mihail/.ssh:/root/.ssh
